/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameState {
  'coolingCount' : bigint,
  'coinBalance' : bigint,
  'totalClicks' : bigint,
  'coinsPerSecond' : bigint,
  'gpuCount' : bigint,
  'lastSaveTimestamp' : Timestamp,
  'cpuCount' : bigint,
}
export type Timestamp = bigint;
export type UpgradeResult = { 'ok' : GameState } |
  { 'insufficientFunds' : { 'available' : bigint, 'required' : bigint } };
export type UpgradeType = { 'cpu' : null } |
  { 'gpu' : null } |
  { 'cooling' : null };
export interface _SERVICE {
  'buyUpgrade' : ActorMethod<[UpgradeType], UpgradeResult>,
  'click' : ActorMethod<[], GameState>,
  'collectCoins' : ActorMethod<[], GameState>,
  'getGameState' : ActorMethod<[], GameState>,
  'getUpgradeCost' : ActorMethod<[UpgradeType], bigint>,
  'loadGameState' : ActorMethod<[], [] | [GameState]>,
  'purchaseUpgrade' : ActorMethod<[UpgradeType], UpgradeResult>,
  'resetGameState' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];