/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UpgradeType = IDL.Variant({
  'cpu' : IDL.Null,
  'gpu' : IDL.Null,
  'cooling' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const GameState = IDL.Record({
  'coolingCount' : IDL.Nat,
  'coinBalance' : IDL.Nat,
  'totalClicks' : IDL.Nat,
  'coinsPerSecond' : IDL.Nat,
  'gpuCount' : IDL.Nat,
  'lastSaveTimestamp' : Timestamp,
  'cpuCount' : IDL.Nat,
});
export const UpgradeResult = IDL.Variant({
  'ok' : GameState,
  'insufficientFunds' : IDL.Record({
    'available' : IDL.Nat,
    'required' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  'buyUpgrade' : IDL.Func([UpgradeType], [UpgradeResult], []),
  'click' : IDL.Func([], [GameState], []),
  'collectCoins' : IDL.Func([], [GameState], []),
  'getGameState' : IDL.Func([], [GameState], []),
  'getUpgradeCost' : IDL.Func([UpgradeType], [IDL.Nat], ['query']),
  'loadGameState' : IDL.Func([], [IDL.Opt(GameState)], ['query']),
  'purchaseUpgrade' : IDL.Func([UpgradeType], [UpgradeResult], []),
  'resetGameState' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UpgradeType = IDL.Variant({
    'cpu' : IDL.Null,
    'gpu' : IDL.Null,
    'cooling' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const GameState = IDL.Record({
    'coolingCount' : IDL.Nat,
    'coinBalance' : IDL.Nat,
    'totalClicks' : IDL.Nat,
    'coinsPerSecond' : IDL.Nat,
    'gpuCount' : IDL.Nat,
    'lastSaveTimestamp' : Timestamp,
    'cpuCount' : IDL.Nat,
  });
  const UpgradeResult = IDL.Variant({
    'ok' : GameState,
    'insufficientFunds' : IDL.Record({
      'available' : IDL.Nat,
      'required' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    'buyUpgrade' : IDL.Func([UpgradeType], [UpgradeResult], []),
    'click' : IDL.Func([], [GameState], []),
    'collectCoins' : IDL.Func([], [GameState], []),
    'getGameState' : IDL.Func([], [GameState], []),
    'getUpgradeCost' : IDL.Func([UpgradeType], [IDL.Nat], ['query']),
    'loadGameState' : IDL.Func([], [IDL.Opt(GameState)], ['query']),
    'purchaseUpgrade' : IDL.Func([UpgradeType], [UpgradeResult], []),
    'resetGameState' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };